Sprint 2
parnasmi/middle.messenger.praktikum.yandex pull request #2
Opened 2022-02-08 18:30 UTC by parnasmi

2022-02-08 22:44 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, все выглядит супер)
В комментах, я зада несколько вопросов, посмотрите их пожалуйста) так же:

- клик в кнопку нет аккаунта, отдает 404
- клик в кнопку профиль из чатов, отдает 404

Удачи)

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/404/404.ts
> +		super("main", {
Тут кажется разъехалось форматирование, для решения таких проблем хорошо подойдет [Prettier](https://prettier.io/)

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/404/404.ts
> +export class NotFound extends Block {
```suggestion
import '../../scss/pages/service-page.scss'

export class NotFound extends Block {
```

Обычно между импортами и началом кода, добавляют пустую строку

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/Chat/Chat.ts
> +const chatJsonItems = [
Моковые данные принято выносить в отдельный файлик, что бы не смешивать логику с данными

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/Chat/Chat.ts
> +		document.title = 'Chat'
Эту логику лучше вынести в css, подключаемый конкретно к странице чата

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/Chat/components/ChatItem/chatItemTypes.types.ts
> +  unread_count:number | null;
Тут немного съехало форматирование, нет проблема между двоеточием и типом
```suggestion
  unread_count: number | null;
```

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/Chat/components/ChatMessage/ChatMessage.types.ts
> +  },
Будет удобней вынести это в отдельный тип `User`

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/NavigationPage/navigation.tmpl.hbs
> +<!--			<li><a href="sign-in">Вход</a></li>-->
Такие комменты лучше удалять из кода, часто через пару недель мы уже и не помним зачем это здесь)

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/ProfileEdit/ProfileEdit.ts
> +const userProfileData:Record<string, string> = {
Тут лучше описать корректный тип `User`

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/ProfilePasswordChange/ProfilePasswordChange.ts
> +	//TODO: _generateFormAfterDidMount
Тут будет лучше оставить этот метод пустым и написать сверху @jsdoc с описанием функционала

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/ProfilePasswordChange/components/PasswordChangeForm.ts
> +            blur: (event: Event) => this._onFocus(index, event),
Ивенты принято называть `onEvent`, в данном случае `onBlur`, `onFocus`

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/pages/SignIn/SignIn.ts
> +		document.body.className = "h-screen not-auth w-screen";
Почему эти классы должны висеть именно на body? Как будто тут стоит описать необходимые свойства в стилях самой страницы

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/scss/pages/chat/_chat.scss
> +  //padding: 2px 0;
Закомменченные стили лучше удалять, раз они не нужны

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/shared/components/Button/button.types.ts
> +  attributes?: {
`ButtonProps`

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/shared/components/EditInputField/EditInputField.ts
> +	componentDidUpdate(oldProps: any, newProps: any): boolean {
Тут не any, а тип пропсов данного компонента

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/shared/components/Form/Form.ts
> +      email:/\S+@\S+\.\S+/,
Люди годами валидировали [email](https://emailregex.com/), стоит воспользоваться трудами предков, главное оставить ссылку на источник). Ваш пример к сожалению не обрабатывает достаточно много кейсов:

`/\S+@\S+\.\S+/.test("asds@asd.ru@asd")`

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/shared/utils/Block/Block.ts
> +export class Block<P = any> {
props лучше типизировать через [[generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)](https://www.typescriptlang.org/docs/handbook/2/generics.html) примерно таким образом, так будет возможность точно передать в базовый блок, тип пропсов наследников.

В общем виде должно получиться, что-то такое:

```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}

```

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/shared/utils/Eventbus/eventBus.ts
> +  private events: {[key in E]?: Listener<M[E]>[]} = {};
Тут кажется достаточно `Record<string, Listeners[]>`, либо создать список всех ивентов которые используются в приложении и вычислить тип из них

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/shared/utils/HTTPTransport/HTTPTransport.ts
> +      xhr.open(options.method, method === HTTPMethods.GET ? `${url}${queryStringify(data)}` : url)
query параметры можно передавать не только для метода get. Тут два варианта решения этой проблемы) Либо формировать url внутри методов get, post... Либо принимать в options два параметра:

- params - их мы перекладываем в query
- data - это поле передаем в body запроса (это поле мы не передаем из метода get)

2022-02-08 22:44 UTC, DmitryKhitrin commented on src/shared/utils/HTTPTransport/HTTPTransport.ts
> +        resolve(xhr)
Тут можно сразу проверить `xhr.status` и если он не 200 к примеру, сразу бросить reject

2022-02-08 22:44 UTC, DmitryKhitrin commented on tsconfig.json
> +    "strict": true,
Отлично!)

2022-02-09 04:32 UTC, parnasmi commented on src/shared/utils/Eventbus/eventBus.ts
> +  private events: {[key in E]?: Listener<M[E]>[]} = {};
Спасибо. Извините, но я не понял что где как поправить.

2022-02-11 05:57 UTC, DmitryKhitrin approved these changes
Спасибо за внесенные правки и удачи в следующем спринте!)

2022-02-11 05:57 UTC, DmitryKhitrin commented on src/shared/utils/Eventbus/eventBus.ts
> +export class EventBus<
В ревью не было комментария поправить, просто идея, что в данном случае можно было сделать проще)

2022-02-11 05:57 UTC, DmitryKhitrin commented on src/shared/utils/HTTPTransport/HTTPTransport.ts
> +      // Просто было написано: В методе GET data трансформируется в формат GET-запроса ?key1=value1&key2=value2
Тут скорее не про ТЗ, а про реализацию корректного функционала. Спасибо, что нашли время поправить эту проблему!)

2022-02-12 05:22 UTC, merged